event_inherited();

dialog.add(sigma, "*пых пых* Чудесно, просто чудесно!");
dialog.add(sigma, "Давай его скорей сюда, я уже заждался!");
dialog.add(PlayerFace, "Да тише ты, никуда твое рагу не убежит.");
dialog.add(PlayerFace, "Держи.");
dialog.add(sigma, "*чавк чавк* Вкуснятина!");
dialog.add(sigma, "Если бы я не видел, как ты это готовишь, подумал бы, что это Маришка!");
dialog.add(PlayerFace, "Доедай быстрее и мигом за работу!");
dialog.add(PlayerFace, "Если не починим приборы, энергии не будет, и с экспедицией мы не свяжемся.");
dialog.add(sigma, "*чавк чавк* Это я помню.");
dialog.add(sigma, "Ох, Божечки, как же вкусно...");
dialog.add(sigma, "Я сейчас заплачу...");
dialog.add(sigma, "*пых пых*");
dialog.add(PlayerFace, "Ты в порядке?");
dialog.add(sigma, "*пых пых*");
dialog.add(sigma, "Ох...");
dialog.add(sigma, "Что-то мне нехорошо...");
dialog.add(PlayerFace, "Я не настолько плохо готовлю.");
dialog.add(PlayerFace, "И даже не думай прикидываться, чтобы отлынивать!");
dialog.add(sigma, "*пых пых, пых пых*");
dialog.add(PlayerFace, "Ну? Чего поник? Как же назвать-то тебя...");
dialog.add(PlayerFace, "Ну чего ты глаза-то закрыл?");
dialog.add(sigma, "...");
dialog.add(PlayerFace, "Уснул что ли?");
dialog.add(sigma, "...");
dialog.add(PlayerFace, "Дрянь...");
dialog.add(PlayerFace, "Непохоже просто на сон. Надо его обследовать. В медкрыле есть инструменты.");
