event_inherited();

dialog.add(PlayerFace, "Скажи, что ты получился удачный...");
dialog.add(sigma, "*чавк чавк* В смысле?");
dialog.add(PlayerFace, "Чем мы сейчас должны заниматься? С какой мыслью я делал Слепок?");
dialog.add(sigma, "*чавк чавк*");
dialog.add(sigma, "Вроде бы поесть хотел?... Нет?...");
dialog.add(sigma, "*чавк чавк*");
dialog.add(sigma, "По крайней мере *чавк*");
dialog.add(sigma, "я только об этом сейчас");
dialog.add(sigma, "*чавк*");
dialog.add(sigma, "и думаю");
dialog.add(PlayerFace, "Ясно, ты тоже неправильный вышел...");
dialog.add(PlayerFace, "Нам нужно починить электрику!");
dialog.add(PlayerFace, "Перестань есть, пошли в инженерный.");
dialog.add(sigma, "*чавк чавк*");
dialog.add(sigma, "Пока я не наемся, никуда не пойду.");
dialog.add(sigma, "А еда тут такая… Скромненькая. ");
dialog.add(PlayerFace, "Ну и что же тебе подавать?");
dialog.add(PlayerFace, "Ты такими темпами всю провизию за пару часов съешь,");
dialog.add(PlayerFace, "а ее тут лет на десять вперед! ");
dialog.add(sigma, "*чавк чавк* Ну... Помнишь, Маришка рагу готовила? ");
dialog.add(PlayerFace, "Когда мы только прилетели? ");
dialog.add(sigma, "*чавк* Ага.");
dialog.add(sigma, "Помнится, там мясо такое вкусное было...");
dialog.add(PlayerFace, "Да чего там только не было.");
dialog.add(PlayerFace, "Готовь себе это рагу, съедай его, и возьмемся за работу.");
dialog.add(PlayerFace, "Я как раз других найду. ");
dialog.add(sigma, "*чавк* Уж не знаю, удастся ли мне приготовить сейчас.");
dialog.add(sigma, "Я со стула-то еле встану...");
dialog.add(PlayerFace, "Тебе пройти до плитки два метра. ");
dialog.add(sigma, "*пых пых* Для меня это как марафон пробежать. ");
dialog.add(PlayerFace, "И какой мне тогда от тебя вообще будет толк?");
dialog.add(PlayerFace, "Зачем мне это рагу тебе готовить, ");
dialog.add(PlayerFace, "если ты, и не поев его, уже не можешь ходить?");
dialog.add(sigma, "*пых пых* Ну будет тебе. Сготовь его, а?");
dialog.add(sigma, "Я как ложечку попробую, сразу полон сил буду. ");
dialog.add(PlayerFace, "Ага, конечно. ");
dialog.add(sigma, "*пых пых* Слово даю, помогу починить...");
dialog.add(sigma, "Что там, электронику? Рагу только навари того.");
dialog.add(sigma, "Только чтоб как Маришка делала, уж больно вкусно было...");
dialog.add(PlayerFace, "Мне рецепт нужен.");
dialog.add(PlayerFace, "Откуда я знаю, что она первым бросала, а что последним?");
dialog.add(sigma, "*пых пых* Ты же помнил его...");
dialog.add(sigma, "Даже я припоминаю, что овощи она не последними жарила.");
dialog.add(PlayerFace, "Разве я его помнил?");
dialog.add(sigma, "*пых пых* Ага. Ты же других, кроме меня, тоже наделал?");
dialog.add(sigma, "Поспрашивай у них, может что-то в памяти осталось.");
dialog.add(PlayerFace, "Поспрашивать-то поспрашиваю… Но почему я-то сам не помню?..");
dialog.add(sigma, "*пых пых* А черт его знает.");
